package com.example.weatherapp.weatherapi

import com.google.gson.annotations.SerializedName

data class Current(
//    val cloud: Int,
//    val condition: Condition,
//    val feelslike_c: Double,
//    val feelslike_f: Double,
//    val gust_kph: Double,
//    val gust_mph: Double,
//    val humidity: Int,
//    val is_day: Int,
//    val last_updated: String,
//    val last_updated_epoch: Int,
//    val precip_in: Double,
//    val precip_mm: Double,
//    val pressure_in: Double,
//    val pressure_mb: Double,
//    val temp_c: Double,
//    val temp_f: Double,
//    val uv: Double,
//    val vis_km: Double,
//    val vis_miles: Double,
//    val wind_degree: Int,
//    val wind_dir: String,
//    val wind_kph: Double,
//    val wind_mph: Double,

    @SerializedName("last_updated_epoch") var lastUpdatedEpoch: Int,
    @SerializedName("last_updated") var lastUpdated: String,
    @SerializedName("temp_c") var tempC: Int,
    @SerializedName("temp_f") var tempF: Double,
    @SerializedName("is_day") var isDay: Int,
    @SerializedName("wind_mph") var windMph: Double,
    @SerializedName("wind_kph") var windKph: Double,
    @SerializedName("wind_degree") var windDegree: Int,
    @SerializedName("wind_dir") var windDir: String,
    @SerializedName("pressure_mb") var pressureMb: Int,
    @SerializedName("pressure_in") var pressureIn: Double,
    @SerializedName("precip_mm") var precipMm: Double,
    @SerializedName("precip_in") var precipIn: Double,
    @SerializedName("humidity") var humidity: Int,
    @SerializedName("cloud") var cloud: Int,
    @SerializedName("feelslike_c") var feelslikeC: Double,
    @SerializedName("feelslike_f") var feelslikeF: Double,
    @SerializedName("vis_km") var visKm: Double,
    @SerializedName("vis_miles") var visMiles: Int,
    @SerializedName("uv") var uv: Int,
    @SerializedName("gust_mph") var gustMph: Double,
    @SerializedName("gust_kph") var gustKph: Double,
)